version: '3'

services:

   app:
      build:
        context: ./
        dockerfile: Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}_app
      restart: unless-stopped
      volumes:
        - ./:/var/www
      networks:
        - sail
      depends_on:
        - postgres
        - rabbitmq
        - redis
        - mailhog
   redis:
      image: redis:alpine
      container_name: ${COMPOSE_PROJECT_NAME}_redis
      restart: unless-stopped
      ports:
       - 6379:6379
      volumes:
       - ./containers/redis:/var/www
      networks:
       - sail

   mailhog:
      image: mailhog/mailhog
      container_name: ${COMPOSE_PROJECT_NAME}_mailhog
      restart: unless-stopped
      environment:
        MAIL_MAILER: ${MAIL_MAILER}
        MAIL_HOST: ${MAIL_HOST}
        MAIL_PORT: ${MAIL_PORT}
        MAIL_USERNAME: ${MAIL_USERNAME}
        MAIL_PASSWORD: ${MAIL_PASSWORD}
        MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      ports:
        - 1025:1025
        - 8025:8025
      networks:
       - sail
      external_links:
        - mailhog
        
   rabbitmq:
      image: rabbitmq:management
      container_name: ${COMPOSE_PROJECT_NAME}_rabbitmq
      restart: unless-stopped
      environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASSWORD: guest
        RABBITMQ_DEFAULT_VHOST: /
      ports:
        - 15671:15671
        - 15672:15672
        - 5671:5671
        - 5672:5672
      networks:
        - sail


   postgres:
      image: postgres:12-alpine
      container_name: ${COMPOSE_PROJECT_NAME}_postgres
      restart: unless-stopped
      volumes:
        - "./containers/postgres:/var/lib/postgresql/data"
      environment:
        - POSTGRES_PORT=${DB_PORT}
        - POSTGRES_HOST=${DB_HOST}
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_USERNAME=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_HOST_AUTH_METHOD=trust
      ports:
        - 5432:5432
      networks:
        - sail
   nginx:
      image: nginx:alpine
      container_name: ${COMPOSE_PROJECT_NAME}_nginx
      restart: unless-stopped
      ports:
        - 8000:80
        - 443:443
      volumes:
        - ./:/var/www
        - ./containers/nginx:/etc/nginx/conf.d/
      networks:
        - sail

networks:
   sail:
      driver: bridge
